### ISSUE TITLE
<div class="placeholder"> Blank convert error 

### ISSUE THREAD

**Issue by name-is-cipher** [cipherusprime/UnoQuack#2]
<div class="placeholder">
Type / Paste Your Text Here...

[UnoQuack]: Conversion Failed !!!

[UnoQuack]: "div" is not a valid command.

[UnoQuack]: "Type" is not a valid command.

**Comment by jvrrs** [comment]
what did you paste in it?

**Comment by jvrrs** [comment]
fixed it
